CREATE TABLE IF NOT EXISTS Bookings (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT,
    ShowtimeId INT,
    TotalPrice DECIMAL(10,2),
    Status ENUM('PENDING', 'PAID', 'CANCELLED') DEFAULT 'PENDING',
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserId) REFERENCES Users(Id),
    FOREIGN KEY (ShowtimeId) REFERENCES Showtimes(Id)
);

CREATE TABLE IF NOT EXISTS BookingSeats (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    BookingId INT,
    SeatId INT,
    Price DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (BookingId) REFERENCES Bookings(Id) ON DELETE CASCADE,
    FOREIGN KEY (SeatId) REFERENCES Seats(Id)
);
